before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: murmur
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - ghcr.io/busser/murmur:{{ .Tag }}
      - ghcr.io/busser/murmur:v{{ .Major }}.{{ .Minor }}
      - ghcr.io/busser/murmur:v{{ .Major }}
      - ghcr.io/busser/murmur:latest
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - '^chore\(deps\):'
      - "^docs:"
      - '^fix\(deps\):'
      - "^refactor:"
      - "^test:"
