before:
  hooks:
    - go mod tidy

builds:
  - id: murmur
    binary: murmur
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    main: ./
  # The project was renamed "murmur" in May 2023. For backwards compatibility,
  # we continue to publish artifacts named "whisper".
  - id: whisper
    binary: whisper
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    main: ./

archives:
  - id: murmur
    builds: [murmur]
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
  # The project was renamed "murmur" in May 2023. For backwards compatibility,
  # we continue to publish artifacts named "whisper".
  - id: whisper
    builds: [whisper]
    name_template: >-
      whisper_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - id: murmur
    ids: [murmur]
    build_flag_templates:
      - --build-arg=BINARY=murmur
      - --platform=amd64
    image_templates:
      - ghcr.io/busser/murmur:{{ .Tag }}
      - ghcr.io/busser/murmur:v{{ .Major }}.{{ .Minor }}
      - ghcr.io/busser/murmur:v{{ .Major }}
      - ghcr.io/busser/murmur:latest
  # The project was renamed "murmur" in May 2023. For backwards compatibility,
  # we continue to publish artifacts named "whisper".
  - id: whisper
    ids: [whisper]
    build_flag_templates:
      - --build-arg=BINARY=whisper
      - --platform=amd64
    image_templates:
      - ghcr.io/busser/whisper:{{ .Tag }}
      - ghcr.io/busser/whisper:v{{ .Major }}.{{ .Minor }}
      - ghcr.io/busser/whisper:v{{ .Major }}
      - ghcr.io/busser/whisper:latest

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - '^chore\(deps\):'
      - "^docs:"
      - '^fix\(deps\):'
      - "^refactor:"
      - "^test:"
