before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: whisper
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - ghcr.io/busser/whisper:{{ .Tag }}
      - ghcr.io/busser/whisper:v{{ .Major }}.{{ .Minor }}
      - ghcr.io/busser/whisper:v{{ .Major }}
      - ghcr.io/busser/whisper:latest
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore(deps):'
