name: Build and test

on: push

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: make build test

  end-to-end-tests:
    runs-on: ubuntu-latest

    # Required for workload identity, which end-to-end tests use to authenticate
    # to Google Cloud and AWS.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      # This service account and the workload identity setup required for
      # Github Actions to use the service account are managed by Terraform.
      # The relevant code is in the terraform/layers/gcp-secret-manager
      # directory of this repository.
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/841223787188/locations/global/workloadIdentityPools/default/providers/github-oidc'
          service_account: 'github-actions@whisper-tests.iam.gserviceaccount.com'
          token_format: 'access_token'
          access_token_lifetime: '300s'

      # This role and the workload identity setup required for Github Actions to
      # use the role are managed by Terraform.
      # The relevant code is in the terraform/layers/aws-secrets-manager
      # directory of this repository.
      - uses: aws-actions/configure-aws-credentials@v1
        timeout-minutes: 1
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::531255069405:role/GithubActions

      - run: make test-e2e
        env:
          # These secrets are managed by Terraform. The relevant code is in the
          # terraform/layers/azure-keyvault directory of this repository.
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
